# Generated by Django 5.0.6 on 2026-06-20 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('total_miles', models.FloatField()),
                ('total_days', models.PositiveSmallIntegerField()),
                ('estimated_start', models.DateTimeField()),
                ('estimated_end', models.DateTimeField(blank=True, null=True)),
                ('locations', models.JSONField()),
                ('route_geometry', models.JSONField()),
                ('assumptions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='trips_trip_created_44654c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('totals', models.JSONField()),
                ('total_hours', models.FloatField()),
                ('miles_today', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('location', 'Location'), ('break', '30-minute break'), ('fuel', 'Fuel stop'), ('rest', '10-hour rest'), ('restart', '34-hour restart')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_hr', models.FloatField()),
                ('text', models.CharField(max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='trips.dailylog')),
            ],
            options={
                'ordering': ['time_hr'],
                'indexes': [models.Index(fields=['daily_log'], name='trips_daily_daily_l_3d887d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLogSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('start_hr', models.FloatField()),
                ('end_hr', models.FloatField()),
                ('label', models.CharField(max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.dailylog')),
            ],
            options={
                'ordering': ['start_hr'],
                'indexes': [models.Index(fields=['daily_log'], name='trips_daily_daily_l_fa5d8e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dailylog',
            index=models.Index(fields=['trip', 'date'], name='trips_daily_trip_id_22efee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'date')},
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'time'], name='trips_trips_trip_id_d150d7_idx'),
        ),
    ]
