# Generated by Django 5.0.6 on 2026-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state_name', models.CharField(blank=True, max_length=255)),
                ('state_id', models.CharField(blank=True, max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-population'],
                'indexes': [models.Index(fields=['name'], name='trips_city_name_521d63_idx'), models.Index(fields=['state_name'], name='trips_city_state_n_0b0589_idx')],
            },
        ),
    ]
